AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CID-like training API (step 1)

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      Handler: app.handler
      CodeUri: src/health/
      MemorySize: 128
      Timeout: 5
      Events:
        HealthApi:
          Type: Api
          Properties:
            Path: /health
            Method: GET
